### ISSUE TITLE
Error with UMD

### ISSUE THREAD

**Issue by Gouigouix** [M-Ulyanov/stickyBlock#3]
@M-Ulyanov 

I tested the UMD integration and that **failed**! You can test with this link: https://repl.it/I3AE/1
Remove comment the "sticky-block" import and run.

I see your implementation of UMD template and I don't know what don't working! 

Thx

**Comment by maxulyanov** [comment]
Thanks, I fixed this

**Comment by Gouigouix** [comment]
Hello @M-Ulyanov, I tested with version 1.2.3 but I have the same problem!
